export const SANSOKIM_ATTENDANCE_INTERSTITIAL_AD_GROUP_ID_PLACEHOLDER =
  "SANSOKIM_ATTENDANCE_INTERSTITIAL_AD_GROUP_ID_PLACEHOLDER";

export const SANSOKIM_ATTENDANCE_INTERSTITIAL_AD_GROUP_ID =
  "ait.v2.live.948d42ee1f4c4045";

export const SANSOKIM_INTERSTITIAL_AD_PRELOAD_TIMEOUT_MS = 15_000;
export const SANSOKIM_INTERSTITIAL_AD_SHOW_SETTLE_TIMEOUT_MS = 15_000;

export const sansokimInterstitialAdConfig = {
  attendanceAdGroupId: SANSOKIM_ATTENDANCE_INTERSTITIAL_AD_GROUP_ID,
} as const;
